development:
  adapter: mysql2
  encoding: utf8
  database: optimization_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: optimization_test
  username: root
  password:
  host: localhost